apiVersion: v1 
kind: Service
metadata: 
  name: myservice
  labels:
    app: projectA
spec:
  type: NodePort 
  selector:
    app: projectA 
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30012
